from django.contrib import admin
from .models import (route,driver,company,station,routeStation,transport,classintrnasport,cart,shipping,payment,useraddress,transportticket,orderStan,order,cyclyce,transportticketstan)
admin.site.register(route)
admin.site.register(driver)
admin.site.register(company)
admin.site.register(station)
admin.site.register(routeStation)
admin.site.register(transport)
admin.site.register(classintrnasport)
admin.site.register(cart)
admin.site.register(shipping)
admin.site.register(payment)
admin.site.register(useraddress)
admin.site.register(transportticket)
admin.site.register(orderStan)
admin.site.register(order)
admin.site.register(cyclyce)
admin.site.register(transportticketstan)