# Generated by Django 3.0.2 on 2020-01-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200107_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
    ]
