# Generated by Django 3.0.2 on 2020-01-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200107_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver'),
        ),
    ]
