# Generated by Django 3.0.2 on 2020-01-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_route_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
