# Generated by Django 3.0.2 on 2020-01-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200107_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
