# Generated by Django 3.0.2 on 2020-01-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200107_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='time',
            field=models.DateField(),
        ),
    ]
