# Generated by Django 3.0.2 on 2020-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200108_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestation',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
