# Generated by Django 3.0.2 on 2020-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200108_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='tickets',
            field=models.BigIntegerField(default=0),
        ),
    ]
