# Generated by Django 3.0.2 on 2020-01-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_routestation_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routestation',
            name='tickets',
        ),
        migrations.AddField(
            model_name='route',
            name='tickets',
            field=models.BigIntegerField(default=0),
        ),
    ]
