# Generated by Django 3.0.2 on 2020-01-08 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200108_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.transport'),
        ),
    ]
