# Generated by Django 3.0.2 on 2020-01-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_route_transport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='title',
            new_name='name',
        ),
    ]
