# Generated by Django 3.0.2 on 2020-01-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200108_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestation',
            name='last',
            field=models.BooleanField(default=False),
        ),
    ]
