# Generated by Django 3.0.2 on 2020-01-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20200113_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
