# Generated by Django 3.0.2 on 2020-01-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_driver_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver'),
        ),
    ]
