# Generated by Django 3.0.2 on 2020-01-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_route_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='driver',
        ),
    ]
