# Generated by Django 3.0.2 on 2020-01-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_route_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
