# Generated by Django 3.0.2 on 2020-01-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_route_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stations',
            field=models.ManyToManyField(blank=True, to='app.routeStation'),
        ),
    ]
