# Generated by Django 3.0.2 on 2020-01-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200117_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='classintrnasport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='transport',
            name='stations',
            field=models.ManyToManyField(blank=True, to='app.classintrnasport'),
        ),
    ]
