# Generated by Django 3.0.2 on 2020-01-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20200120_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='stations',
            new_name='classs',
        ),
    ]
