# Generated by Django 3.0.2 on 2020-01-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200120_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.BigIntegerField(default=0)),
                ('quantity', models.BigIntegerField(default=0)),
                ('route', models.ManyToManyField(blank=True, to='app.route')),
            ],
        ),
    ]
