# Generated by Django 3.0.2 on 2020-01-21 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_cart_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='route',
        ),
        migrations.AddField(
            model_name='cart',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.route'),
        ),
    ]
