# Generated by Django 3.0.2 on 2020-01-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_payment_shipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='payment',
        ),
    ]
