# Generated by Django 3.0.2 on 2020-01-22 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useraddress',
        ),
    ]
