# Generated by Django 3.0.2 on 2020-01-22 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
