# Generated by Django 3.0.2 on 2020-01-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20200122_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='name',
            new_name='name2',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='price',
            new_name='price2',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='stan',
            new_name='stan2',
        ),
    ]
