# Generated by Django 3.0.2 on 2020-01-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_auto_20200122_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='tickets',
        ),
        migrations.AddField(
            model_name='route',
            name='tickets',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='transportticket',
        ),
    ]
