# Generated by Django 3.0.2 on 2020-01-22 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_transportticket_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportticket',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.company'),
        ),
    ]
