# Generated by Django 3.0.2 on 2020-01-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_transportticket_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportticket',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.route'),
        ),
        migrations.RemoveField(
            model_name='route',
            name='tickets',
        ),
        migrations.AddField(
            model_name='route',
            name='tickets',
            field=models.BigIntegerField(default=0),
        ),
    ]
