# Generated by Django 3.0.2 on 2020-01-22 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_auto_20200122_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportticket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='transportticket',
            name='price',
        ),
        migrations.AddField(
            model_name='transportticket',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cart'),
        ),
    ]
