# Generated by Django 3.0.2 on 2020-01-22 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_auto_20200122_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportticket',
            name='cart',
        ),
    ]
