# Generated by Django 3.0.2 on 2020-01-22 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_remove_transportticket_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transportticket',
        ),
    ]
