# Generated by Django 3.0.2 on 2020-01-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_transportticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportticket',
            name='company',
        ),
        migrations.RemoveField(
            model_name='transportticket',
            name='route',
        ),
        migrations.RemoveField(
            model_name='route',
            name='tickets',
        ),
        migrations.AddField(
            model_name='route',
            name='tickets',
            field=models.ManyToManyField(blank=True, to='app.transportticket'),
        ),
    ]
