# Generated by Django 3.0.2 on 2020-01-31 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_order_orderstan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stations',
            new_name='Items',
        ),
    ]
