# Generated by Django 3.0.2 on 2020-02-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_auto_20200131_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportticket',
            name='invalid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
