# Generated by Django 3.0.2 on 2020-02-03 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_auto_20200203_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='user',
            new_name='cyclycetype',
        ),
    ]
