# Generated by Django 3.0.2 on 2020-02-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_auto_20200203_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='cyclycetvalue',
            field=models.BigIntegerField(default=0),
        ),
    ]
